[build]
  publish = "."

[[headers]]
  for = "/public/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/public/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
